# Generated by Django 3.1.1 on 2020-09-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
